; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "27Launcher"
#define MyAppVersion "1.0"
#define MyAppPublisher "PopU27"
#define MyAppURL "https://github.com/PopU27/27Launcher"
#define MyAppExeName "27Launcher.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{FE3EAAB3-C50C-4D43-B1C4-18B29DE98E5C}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=commandline
OutputBaseFilename=27LauncherSetup
SolidCompression=yes
WizardStyle=modern dynamic

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "E:\rodgo\CodeProjects\27Launcher\build\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
; Source: "E:\rodgo\CodeProjects\27Launcher\deploy\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
Source: "E:\msys64\ucrt64\bin\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

; NOTE: Don't use "Flags: ignoreversion" on any shared system files
;Source: "E:\msys64\ucrt64\bin\libgcc_s_seh-1.dll"; DestDir: "{app}"; Flags: ignoreversion
;Source: "E:\msys64\ucrt64\bin\libstdc++-6.dll"; DestDir: "{app}"; Flags: ignoreversion
;Source: "E:\msys64\ucrt64\bin\libwinpthread-1.dll"; DestDir: "{app}"; Flags: ignoreversion


; For QT6
;Source: "E:\msys64\ucrt64\bin\Qt6Core.dll"; DestDir: "{app}"; Flags: ignoreversion
;Source: "E:\msys64\ucrt64\bin\Qt6Widgets.dll"; DestDir: "{app}"; Flags: ignoreversion
;Source: "E:\msys64\ucrt64\bin\Qt6Gui.dll"; DestDir: "{app}"; Flags: ignoreversion
;Source: "E:\msys64\ucrt64\bin\libpsl-5.dll"; DestDir: "{app}"; Flags: ignoreversion
;Source: "E:\msys64\ucrt64\bin\libngtcp2_crypto_ossl-0.dll"; DestDir: "{app}"; Flags: ignoreversion
;Source: "E:\msys64\ucrt64\bin\libssh2-1.dll"; DestDir: "{app}"; Flags: ignoreversion
;Source: "E:\msys64\ucrt64\bin\libbrotlicommon.dll"; DestDir: "{app}"; Flags: ignoreversion
;Source: "E:\msys64\ucrt64\bin\libiconv-2.dll"; DestDir: "{app}"; Flags: ignoreversion
;Source: "E:\msys64\ucrt64\bin\libintl-8.dll"; DestDir: "{app}"; Flags: ignoreversion
;Source: "E:\msys64\ucrt64\bin\libunistring-5.dll"; DestDir: "{app}"; Flags: ignoreversion
;Source: "E:\msys64\ucrt64\bin\libzstd.dll"; DestDir: "{app}"; Flags: ignoreversion
;Source: "E:\msys64\ucrt64\bin\libb2-1.dll"; DestDir: "{app}"; Flags: ignoreversion
;Source: "E:\msys64\ucrt64\bin\libdouble-conversion.dll"; DestDir: "{app}"; Flags: ignoreversion

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; WorkingDir: "{app}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

